### Dataset and DataLoader classes

In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torchinfo import summary
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [4]:
df.shape

(569, 33)

In [5]:
# dropping of the unnecessary columns
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [6]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [7]:
# train testv split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [8]:
# scaling for features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train

array([[ 0.21996019, -0.15948223,  0.22619546, ..., -0.47495143,
        -0.0767251 ,  0.4196418 ],
       [-0.35716646, -1.22886702, -0.29703515, ...,  0.60215155,
        -0.42169438,  1.82501831],
       [-0.66253929, -0.50599962, -0.69037143, ..., -0.9307581 ,
        -0.19495401, -0.18211387],
       ...,
       [ 1.47787214, -0.14800814,  1.45450875, ...,  1.34812573,
         0.59377858,  0.30499555],
       [-0.31234109, -0.0355621 , -0.39202039, ..., -1.56535937,
        -0.7456092 , -1.18705133],
       [-1.02394384,  0.16638181, -0.95909034, ..., -0.81415292,
        -0.83630535,  0.31432085]])

In [10]:
y_train

147    B
247    B
399    B
88     B
504    B
      ..
135    M
466    B
487    M
58     B
113    B
Name: diagnosis, Length: 455, dtype: object

In [11]:
# label encoding for target variable
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.transform(y_test)
y_train

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,

In [12]:
# Convert numpy arrays to PyTorch tensors (Fixing dtype issue)
X_train_tensor = torch.from_numpy(X_train).to(torch.float64)
X_test_tensor = torch.from_numpy(X_test).to(torch.float64)
y_train_tensor = torch.from_numpy(y_train).to(torch.float64)  # Convert to float64
y_test_tensor = torch.from_numpy(y_test).to(torch.float64)    # Convert to float64

In [13]:
# Convert all tensors to float32 (fixes dtype mismatch issue)
X_train_tensor = X_train_tensor.to(torch.float32)
X_test_tensor = X_test_tensor.to(torch.float32)
y_train_tensor = y_train_tensor.to(torch.float32)
y_test_tensor = y_test_tensor.to(torch.float32)

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

In [16]:
# Defining the model architecture
class NN(nn.Module):

  # creating constructor
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1) # single neuron
    self.sigmoid = nn.Sigmoid() # activation function
  
  # forward pass
  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [17]:
# Important Parameters
learning_rate = 0.1
epochs = 25

In [18]:
# calling loss function from Pytorch.nn
loss_function = nn.BCELoss() # binary cross entropy

In [19]:
# Training pipeline by creating a model
model = NN(X_train_tensor.shape[1])

# defining optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate) # for weights update

# defining loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculation
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1)) # BCELoss
  
  
  # zero gradients
  optimizer.zero_grad() # reset gradients

  # backward pass
  loss.backward()

  #  parameter update
  optimizer.step() # update weights

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # printing loss
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6022382974624634
Epoch: 2, Loss: 0.4755207896232605
Epoch: 3, Loss: 0.4041130244731903
Epoch: 4, Loss: 0.35795333981513977
Epoch: 5, Loss: 0.32529738545417786
Epoch: 6, Loss: 0.30076074600219727
Epoch: 7, Loss: 0.28151631355285645
Epoch: 8, Loss: 0.26592931151390076
Epoch: 9, Loss: 0.25298506021499634
Epoch: 10, Loss: 0.2420189380645752
Epoch: 11, Loss: 0.23257650434970856
Epoch: 12, Loss: 0.2243359237909317
Epoch: 13, Loss: 0.2170625776052475
Epoch: 14, Loss: 0.21058104932308197
Epoch: 15, Loss: 0.2047574520111084
Epoch: 16, Loss: 0.19948753714561462
Epoch: 17, Loss: 0.19468890130519867
Epoch: 18, Loss: 0.19029538333415985
Epoch: 19, Loss: 0.18625320494174957
Epoch: 20, Loss: 0.18251818418502808
Epoch: 21, Loss: 0.17905354499816895
Epoch: 22, Loss: 0.17582841217517853
Epoch: 23, Loss: 0.1728166788816452
Epoch: 24, Loss: 0.16999612748622894
Epoch: 25, Loss: 0.16734756529331207


In [20]:
model.linear.weight

Parameter containing:
tensor([[ 0.3935,  0.1038,  0.1221,  0.3702,  0.1293,  0.1747,  0.1298,  0.0999,
          0.0121, -0.0454,  0.1980,  0.1300,  0.3108,  0.1464, -0.1279,  0.0248,
         -0.1098,  0.1815, -0.0881, -0.1706,  0.2890,  0.1874,  0.2713,  0.3369,
          0.2371,  0.2375,  0.2080,  0.0942,  0.1792,  0.1760]],
       requires_grad=True)

In [21]:
model.linear.bias

Parameter containing:
tensor([-0.0293], requires_grad=True)

In [22]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")


Accuracy: 0.5646352767944336
