### Dataset and DataLoader classes

In [108]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torchinfo import summary
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [109]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [111]:
df.shape

(569, 33)

In [112]:
# dropping of the unnecessary columns
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [113]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [114]:
# train testv split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [115]:
# scaling for features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [116]:
X_train

array([[ 0.54558153,  0.34178673,  0.63600831, ...,  1.35585735,
         1.27223712,  1.596594  ],
       [ 2.49868398,  1.83923256,  2.45108115, ...,  2.12642998,
         0.31745638,  0.12994989],
       [-0.07786642, -0.72237588, -0.14679183, ..., -0.89273285,
        -0.85583141, -0.70629925],
       ...,
       [ 2.09592556,  0.41558772,  2.20320777, ...,  1.01206341,
        -0.11005739,  0.22672808],
       [-0.90821083,  0.53224089, -0.94678319, ..., -1.71606006,
        -0.70382651, -0.98487074],
       [ 0.38006438,  3.4080987 ,  0.46009816, ...,  1.268427  ,
         0.96506056,  1.92809942]])

In [117]:
y_train

17     M
236    M
357    B
184    M
28     M
      ..
330    M
83     M
272    M
550    B
259    M
Name: diagnosis, Length: 455, dtype: object

In [118]:
# label encoding for target variable
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.transform(y_test)
y_train

array([1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,

In [119]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
  # constructor

  # inherits from Dataset class
  def __init__(self, features, labels):

    self.features = features
    self.labels = labels
    
  # returns the number of samples in the dataset
  def __len__(self):

    return self.features.shape[0]
  
  # gets a sample from the dataset
  def __getitem__(self, index):

    return self.features[index], self.labels[index]

In [120]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_train_tensor)

In [121]:
train_dataset[0]

(tensor([-1.3123, -0.5529, -1.2783, -1.0745, -0.8432, -0.2751, -0.0976, -0.6948,
          0.8576,  1.1525, -0.7849, -0.5143, -0.7112, -0.6057, -0.3551,  0.4650,
          0.5374, -0.5758, -0.3714,  0.0489, -1.1658, -0.4176, -1.0997, -0.9348,
         -0.4116,  0.5228,  0.7300, -0.5480,  0.1197,  0.7676]),
 tensor(0.))

In [122]:
# crating data loader
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [123]:
X_train_tensor.shape

torch.Size([455, 30])

In [124]:
y_train_tensor.shape

torch.Size([455])

In [125]:
# Defining the model architecture
class NN(nn.Module):

  # creating constructor
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1) # single neuron
    self.sigmoid = nn.Sigmoid() # activation function
  
  # forward pass
  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    
    return out

In [126]:
# Important Parameters
learning_rate = 0.1
epochs = 25

In [127]:
# calling loss function from Pytorch.nn
loss_function = nn.BCELoss() # binary cross entropy

In [128]:
# Convert all tensors to float32 (fixes dtype mismatch issue)
X_train_tensor = X_train_tensor.to(torch.float32)
X_test_tensor = X_test_tensor.to(torch.float32)
y_train_tensor = y_train_tensor.to(torch.float32)
y_test_tensor = y_test_tensor.to(torch.float32)

In [129]:
# Training pipeline by creating a model
model = NN(X_train_tensor.shape[1])

# defining optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate) # for weights update

# defining loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculation
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1)) # BCELoss
  
  
  # zero gradients
  optimizer.zero_grad() # reset gradients

  # backward pass
  loss.backward()

  #  parameter update
  optimizer.step() # update weights

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # printing loss
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.5662342309951782
Epoch: 2, Loss: 0.4730672240257263
Epoch: 3, Loss: 0.41433414816856384
Epoch: 4, Loss: 0.37337347865104675
Epoch: 5, Loss: 0.34282585978507996
Epoch: 6, Loss: 0.3189491331577301
Epoch: 7, Loss: 0.29963219165802
Epoch: 8, Loss: 0.28358879685401917
Epoch: 9, Loss: 0.2699875831604004
Epoch: 10, Loss: 0.25826552510261536
Epoch: 11, Loss: 0.24802649021148682
Epoch: 12, Loss: 0.23898299038410187
Epoch: 13, Loss: 0.230920672416687
Epoch: 14, Loss: 0.22367604076862335
Epoch: 15, Loss: 0.2171219140291214
Epoch: 16, Loss: 0.2111576646566391
Epoch: 17, Loss: 0.2057022750377655
Epoch: 18, Loss: 0.20068980753421783
Epoch: 19, Loss: 0.196065753698349
Epoch: 20, Loss: 0.19178465008735657
Epoch: 21, Loss: 0.18780812621116638
Epoch: 22, Loss: 0.1841035634279251
Epoch: 23, Loss: 0.1806429624557495
Epoch: 24, Loss: 0.17740210890769958
Epoch: 25, Loss: 0.17435996234416962


In [130]:
# creating a training loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculation
    loss = loss_function(y_pred, batch_labels.view(-1, 1))

    # zero gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    #  parameter update
    optimizer.step()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.26652687788009644
Epoch: 1, Loss: 0.14996136724948883
Epoch: 1, Loss: 0.08915184438228607
Epoch: 1, Loss: 0.21076834201812744
Epoch: 1, Loss: 0.12370183318853378
Epoch: 1, Loss: 0.1475113183259964
Epoch: 1, Loss: 0.18512603640556335
Epoch: 1, Loss: 0.21626272797584534
Epoch: 1, Loss: 0.13739071786403656
Epoch: 1, Loss: 0.13061213493347168
Epoch: 1, Loss: 0.16008611023426056
Epoch: 1, Loss: 0.1287924349308014
Epoch: 1, Loss: 0.15186132490634918
Epoch: 1, Loss: 0.14848043024539948
Epoch: 1, Loss: 0.026309428736567497
Epoch: 2, Loss: 0.13826222717761993
Epoch: 2, Loss: 0.17157159745693207
Epoch: 2, Loss: 0.08943293988704681
Epoch: 2, Loss: 0.06233600527048111
Epoch: 2, Loss: 0.1765890121459961
Epoch: 2, Loss: 0.14231185615062714
Epoch: 2, Loss: 0.09229631721973419
Epoch: 2, Loss: 0.1954343020915985
Epoch: 2, Loss: 0.1273755133152008
Epoch: 2, Loss: 0.16555719077587128
Epoch: 2, Loss: 0.14986552298069
Epoch: 2, Loss: 0.13366523385047913
Epoch: 2, Loss: 0.10666371881961823

In [131]:
model.linear.weight

Parameter containing:
tensor([[ 0.5418,  0.5976,  0.6116,  0.5072,  0.0875,  0.1720,  0.4633,  0.4983,
          0.1877, -0.4402,  0.6465, -0.1085,  0.3180,  0.5328,  0.1359, -0.2760,
         -0.0498,  0.1183, -0.1812, -0.4753,  0.5580,  0.7156,  0.5502,  0.7970,
          0.7764,  0.2247,  0.5591,  0.5266,  0.4552,  0.1432]],
       requires_grad=True)

In [132]:
model.linear.bias

Parameter containing:
tensor([-0.3230], requires_grad=True)

In [135]:
# model evaluation using test loader
model.eval() # evaluation mode
accuracy_list = [] # list to store accuracy

with torch.no_grad(): # no gradient calculation
  for batch_features, batch_labels in test_loader: # iterating over test loader

    # forward pass
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float() # converting to 0 and 1

    # calculating accuracy
    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item() # converting to float
    accuracy_list.append(batch_accuracy) # appending accuracy to list

# calculating overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print(f'Accuracy: {overall_accuracy:.2f}%')

Accuracy: 0.50%
