In [1]:
import torch
print(torch.__version__)

2.3.0


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f'Using GPU: {torch.cuda.get_device_name(0)}')
else:
    print("GPU is not available. Using CPU instead.")

GPU is not available. Using CPU instead.


### Creating Tensors

In [3]:
# Creating empty tensors
a = torch.empty(2, 3)

In [4]:
# Checking type of tensor
type(a)

torch.Tensor

In [5]:
# Using zeros
torch.zeros(2, 3) # 2x3 tensor with zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# Using ones
torch.ones(2, 3) # 2x3 matrix of ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# Using rand
torch.rand(2, 3) # 2x3 matrix of random numbers

tensor([[0.4314, 0.8501, 0.3583],
        [0.1764, 0.0721, 0.5373]])

In [8]:
# Using seed
torch.rand(2, 3)

tensor([[0.4537, 0.9919, 0.7838],
        [0.8760, 0.4952, 0.1869]])

In [9]:
# Manual seed
torch.manual_seed(100) # for same random numbers
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
# Using tensor
torch.tensor([[1, 2, 3], [4, 5, 6]]) # tensor function used to create tensor from list

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# arrange function
print("using arrange function:",torch.arange(0, 10, 2)) # start, end, step

using arrange function: tensor([0, 2, 4, 6, 8])


In [12]:
# using linspace
print("using linspace function:",torch.linspace(0, 10, 10)) # start, end, steps

using linspace function: tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [13]:
# using eye function
print("using eye function:",torch.eye(3)) # 3x3 identity matrix

using eye function: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [14]:
# using full function
print("using full function:",torch.full((2, 3), 5)) # 2x3 matrix with all elements as 5

using full function: tensor([[5, 5, 5],
        [5, 5, 5]])


### Tensor Shapes

In [15]:
# shape attribute
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
print(x.shape) # 2x3 matrix

torch.Size([2, 3])


In [17]:
# using empty_like function to create same shape tensor
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
# using zeros_like function to create same shape tensor but with zeros
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
# using rand_like function to create same shape tensor but with random numbers
torch.rand_like(x, dtype=torch.float) # specify data type

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

### Tensor Data Types

In [20]:
# finding the datatype of tensor
x.dtype

torch.int64

In [21]:
# assigning datatype to tensor (int)
torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [22]:
# assigning datatype to tensor (float)
torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [23]:
# using to function to change the already created tensor datatype
x.to(torch.float)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Mathematical Operations

#### Scalar Operations

In [24]:
x = torch.rand(2, 2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [25]:
# addition in tensors
x + 2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [26]:
# subtraction in tensors
x - 2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [27]:
# multiplication in tensors
x * 2

tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])

In [28]:
# division in tensors
x / 2

tensor([[0.3559, 0.3938],
        [0.2092, 0.4507]])

In [29]:
# integer division in tensors
x // 2

tensor([[0., 0.],
        [0., 0.]])

In [30]:
# using mod function in tensors
x % 2

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [31]:
# using power function in tensors
x ** 2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

#### Element wise Operations

In [32]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [33]:
# element wise addition
a + b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [34]:
# element wise subtraction
a - b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [35]:
# element wise multiplication
a * b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [36]:
# element wise division
a / b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [37]:
# element wise integer division
a // b

tensor([[1., 0., 0.],
        [0., 0., 1.]])

In [38]:
# element wise power
a ** b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [39]:
# element wise mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [40]:
c = torch.tensor([1, -2, 3, -4])
c

tensor([ 1, -2,  3, -4])

In [41]:
# abs value
torch.abs(c)

tensor([1, 2, 3, 4])

In [42]:
# negative value
torch.neg(c)

tensor([-1,  2, -3,  4])

In [43]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [44]:
# rounding the tensor
torch.round(d)

tensor([2., 2., 4., 4.])

In [45]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [46]:
# floor is the opposite of ceil
torch.floor(d)

tensor([1., 2., 3., 4.])

In [47]:
# clamp for keeping them in range
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

#### Reduction Operations

In [48]:
e = torch.randint(size=(2, 3), low=0, high=10, dtype=float)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]], dtype=torch.float64)

In [49]:
# using sum function
torch.sum(e)

tensor(24., dtype=torch.float64)

In [50]:
# sum along columns
torch.sum(e, dim=0) # 0 for columns

tensor([ 8.,  0., 16.], dtype=torch.float64)

In [51]:
# sum along rows
torch.sum(e, dim=1) # 1 for rows

tensor([15.,  9.], dtype=torch.float64)

In [52]:
# mean function
torch.mean(e)

tensor(4., dtype=torch.float64)

In [53]:
# mean for columns and rows
torch.mean(e, dim=0)

tensor([4., 0., 8.], dtype=torch.float64)

In [54]:
# calculating median
torch.median(e)

tensor(0., dtype=torch.float64)

In [55]:
# max and min
torch.min(e)
torch.max(e)

tensor(9., dtype=torch.float64)

In [56]:
# product
torch.prod(e)

tensor(0., dtype=torch.float64)

In [57]:
# standard deviation function
torch.std(e)

tensor(4.4272, dtype=torch.float64)

In [58]:
# calculating variance
torch.var(e)

tensor(19.6000, dtype=torch.float64)

In [59]:
# argmax (for telling the position of the biggest item in the tensor)
torch.argmax(e)


tensor(5)

In [60]:
# argmin (for the minimum item)
torch.argmin(e)

tensor(1)

#### Matrix Operations

In [61]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [62]:
# Matrix Multiplication
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [63]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

print(vector1)
print(vector2)

tensor([1, 2])
tensor([3, 4])


In [64]:
# Dot Product
torch.dot(vector1, vector2)

tensor(11)

In [65]:
# Transpose (swapping)
torch.transpose(f, 0, 1) # name of the matrix, postiton of the dimension, with whom

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [66]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [67]:
# Determinant (work only if you have a square matrix)
torch.det(h)

tensor(-110.)

In [68]:
# Inverse (work only if you have a square matrix)
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

#### Comparison Operations

In [69]:
i = torch.randint(size=(2, 3), low=0, high=10)
j = torch.randint(size=(2, 3), low=0, high=10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [70]:
# Greater than
i > j

tensor([[ True,  True, False],
        [ True, False, False]])

In [71]:
# less than
i < j

tensor([[False, False,  True],
        [False,  True,  True]])

In [72]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [73]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

In [74]:
# greater than equal to
i >= j

tensor([[ True,  True, False],
        [ True, False, False]])

In [75]:
# less than equal to
i <= j

tensor([[False, False,  True],
        [False,  True,  True]])

#### Special Functions

In [76]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [77]:
# log
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [78]:
# exponents
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [79]:
# squareroot
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [80]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [81]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [82]:
# relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

#### Inplace Operations

In [83]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [84]:
m.add_(n) # _ inplace operation help in changing permanently

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [85]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [86]:
n

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [87]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [88]:
m.relu_() # _ inplace operation help in changing permanently

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [89]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

#### Copying a Tensor

In [90]:
l = torch.rand(2,3)
l

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [91]:
r = l # not a right way to copy a tensor

In [92]:
r

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [93]:
l[0, 0] = 0

In [94]:
l

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [95]:
r

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [96]:
id(l) # same memory location

2337633334864

In [97]:
id(r) # same id

2337633334864

In [98]:
# use clone function to copy a tensor (right way)
r = l.clone()

In [99]:
l # original tensor

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [100]:
r # now both are different tensors

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [101]:
l[0, 0] = 1 # changing the value of l

In [102]:
l # original tensor

tensor([[1.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [103]:
r # copied tensor

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

#### Tensors Operations for GPU (Future)

In [105]:
torch.cuda.is_available()

False

In [106]:
device = torch.device('cuda')

In [108]:
# creating tensor on GPU
# torch.rand(2, 3, device=device) this code will not work as I don't have GPU

In [ ]:
# moving an existing tensor to GPU using to function
# l.to(device)

#### Testing out the speed of tensors multiplication of CPU vs GPU

In [119]:
import time

# Defining the size of the matrices
size = 10000 # using larger size to see the difference

# Creating two random matrices on CPU
matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

# Measure the time taken for the matrix multiplication on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) # matrix multiplication
end_time = time.time() - start_time # time taken

print(f"Time taken on CPU: {end_time:.4f} seconds")

Time taken on CPU: 6.1346 seconds


In [ ]:
# Creating two random matrices on GPU - but will test it on the GPU
#matrix_gpu1 = torch.rand(size, size, device=device)
#matrix_gpu2 = torch.rand(size, size, device=device)

# Measure the time taken for the matrix multiplication on GPU
#start_time = time.time()
#result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) # matrix multiplication
#end_time = time.time() - start_time # time taken

#print(f"Time taken on GPU: {end_time} seconds")

# It took less time on GPU as compared to CPU tested it on google colab