In [13]:
import torch
print(torch.__version__)

2.3.0


In [14]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f'Using GPU: {torch.cuda.get_device_name(0)}')
else:
    print("GPU is not available. Using CPU instead.")

GPU is not available. Using CPU instead.


### Creating Tensors

In [17]:
# Creating empty tensors
a = torch.empty(2, 3)

In [18]:
# Checking type of tensor
type(a)

torch.Tensor

In [19]:
# Using zeros
torch.zeros(2, 3) # 2x3 tensor with zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [20]:
# Using ones
torch.ones(2, 3) # 2x3 matrix of ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [21]:
# Using rand
torch.rand(2, 3) # 2x3 matrix of random numbers

tensor([[0.2770, 0.3873, 0.5314],
        [0.8709, 0.5469, 0.3068]])

In [23]:
# Using seed
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [25]:
# Manual seed
torch.manual_seed(100) # for same random numbers
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# Using tensor
torch.tensor([[1, 2, 3], [4, 5, 6]]) # tensor function used to create tensor from list

tensor([[1, 2, 3],
        [4, 5, 6]])

In [30]:
# arrange function
print("using arrange function:",torch.arange(0, 10, 2)) # start, end, step

using arrange function: tensor([0, 2, 4, 6, 8])


In [34]:
# using linspace
print("using linspace function:",torch.linspace(0, 10, 10)) # start, end, steps

using linspace function: tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [32]:
# using eye function
print("using eye function:",torch.eye(3)) # 3x3 identity matrix

using eye function: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [33]:
# using full function
print("using full function:",torch.full((2, 3), 5)) # 2x3 matrix with all elements as 5

using full function: tensor([[5, 5, 5],
        [5, 5, 5]])


### Tensor Shapes

In [36]:
# shape attribute
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [39]:
print(x.shape) # 2x3 matrix

torch.Size([2, 3])


In [40]:
# using empty_like function to create same shape tensor
torch.empty_like(x)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [41]:
# using zeros_like function to create same shape tensor but with zeros
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [47]:
# using rand_like function to create same shape tensor but with random numbers
torch.rand_like(x, dtype=torch.float) # specify data type

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

### Tensor Data Types

In [43]:
# finding the datatype of tensor
x.dtype

torch.int64

In [44]:
# assigning datatype to tensor (int)
torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [45]:
# assigning datatype to tensor (float)
torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [46]:
# using to function to change the already created tensor datatype
x.to(torch.float)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Mathematical Operations

#### Scalar Operations

In [49]:
x = torch.rand(2, 2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [50]:
# addition in tensors
x + 2

tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])

In [51]:
# subtraction in tensors
x - 2

tensor([[-1.7761, -1.6977],
        [-1.8216, -1.1762]])

In [52]:
# multiplication in tensors
x * 2

tensor([[0.4478, 0.6047],
        [0.3568, 1.6477]])

In [53]:
# division in tensors
x / 2

tensor([[0.1119, 0.1512],
        [0.0892, 0.4119]])

In [55]:
# integer division in tensors
x // 2

tensor([[0., 0.],
        [0., 0.]])

In [56]:
# using mod function in tensors
x % 2

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [57]:
# using power function in tensors
x ** 2

tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])

#### Element wise Operations

In [58]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [59]:
# element wise addition
a + b

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [62]:
# element wise subtraction
a - b

tensor([[ 0.3132,  0.2767, -0.0837],
        [ 0.7007, -0.0464,  0.0657]])

In [63]:
# element wise multiplication
a * b

tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])

In [65]:
# element wise division
a / b

tensor([[2.2912, 1.3951, 0.8415],
        [3.8346, 0.9413, 1.1552]])

In [66]:
# element wise integer division
a // b

tensor([[2., 1., 0.],
        [3., 0., 1.]])

In [67]:
# element wise power
a ** b

tensor([[0.8672, 0.9839, 0.6515],
        [0.9868, 0.7919, 0.7388]])

In [68]:
# element wise mod
a % b

tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])