In [1]:
import torch
import torch.nn as nn

In [2]:
# creating model class
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1) # single neuron
    self.sigmoid = nn.Sigmoid() # activation function

  # forward pass
  def forward(self, features):

    out = self.linear(features) # calculating  z = wx + b
    out = self.sigmoid(out)

    return out

In [3]:
# creating a random dataset
features = torch.rand(10, 5) # 10 rows 5 columns (features)

In [5]:
# creating a model
model = Model(features.shape[1])

In [6]:
# calling model for forward pass
# model.forward(features) another option
model(features) # standard way of calling

tensor([[0.4324],
        [0.4442],
        [0.4445],
        [0.3845],
        [0.4355],
        [0.4946],
        [0.4106],
        [0.5191],
        [0.4747],
        [0.4113]], grad_fn=<SigmoidBackward0>)

In [9]:
# viewing model weights
model.linear.weight

Parameter containing:
tensor([[-0.4315, -0.0755,  0.3822, -0.2786,  0.4291]], requires_grad=True)

In [13]:
from torchinfo import summary

In [16]:
# summary of model
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [27]:
# creating and testing a neural network with hidden layer and sequential container

# creating model class
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3), # single neuron
        nn.ReLU(), # activation function
        nn.Linear(3, 1),
        nn.Sigmoid(),
    )

  # forward pass
  def forward(self, features):

    out = self.network(features)
    #out = self.linear1(features) # calculating  z = wx + b
    #out = self.relu(out)
    #out = self.linear2(out)
    #out = self.sigmoid(out)

    return out

In [28]:
# dataset
features = torch.rand(10, 3) 
model = Model(features.shape[1])
model(features)

tensor([[0.4188],
        [0.4603],
        [0.4204],
        [0.4063],
        [0.4537],
        [0.4307],
        [0.4763],
        [0.4151],
        [0.4488],
        [0.4321]], grad_fn=<SigmoidBackward0>)

In [33]:
# summary of model
summary(model, input_size=(10, 3))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   12
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 16
Trainable params: 16
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00