In [128]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torchinfo import summary
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [129]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [131]:
df.shape

(569, 33)

In [132]:
# dropping of the unnecessary columns
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [133]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [134]:
# train testv split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [135]:
# scaling for features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [136]:
X_train

array([[-0.7413417 , -1.00407365, -0.7439486 , ..., -0.2681256 ,
        -0.36222847, -0.3063054 ],
       [ 0.25800885,  1.37467203,  0.16073187, ..., -1.30437431,
        -2.09139824, -1.68975563],
       [-0.06166813, -0.71918006, -0.13860173, ..., -1.05137455,
        -0.55418362, -1.01813706],
       ...,
       [-0.63478271, -0.44123509, -0.64667562, ..., -0.37037581,
        -1.06081935, -1.3722523 ],
       [-0.15382726, -1.24264308, -0.12941715, ..., -0.34813407,
         0.26870609, -0.08543352],
       [-1.30380038, -0.77708526, -1.31422711, ..., -0.63665883,
        -0.215902  , -0.08483332]])

In [137]:
y_train

249    B
38     M
387    B
187    B
206    B
      ..
172    M
384    B
275    B
221    B
234    B
Name: diagnosis, Length: 455, dtype: object

In [138]:
# label encoding for target variable
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.transform(y_test)
y_train

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,

In [139]:
# Convert numpy arrays to PyTorch tensors (Fixing dtype issue)
X_train_tensor = torch.from_numpy(X_train).to(torch.float64)
X_test_tensor = torch.from_numpy(X_test).to(torch.float64)
y_train_tensor = torch.from_numpy(y_train).to(torch.float64)  # Convert to float64
y_test_tensor = torch.from_numpy(y_test).to(torch.float64)    # Convert to float64

In [140]:
# Convert all tensors to float32 (fixes dtype mismatch issue)
X_train_tensor = X_train_tensor.to(torch.float32)
X_test_tensor = X_test_tensor.to(torch.float32)
y_train_tensor = y_train_tensor.to(torch.float32)
y_test_tensor = y_test_tensor.to(torch.float32)

In [141]:
X_train_tensor.shape

torch.Size([455, 30])

In [142]:
y_train_tensor.shape

torch.Size([455])

In [143]:
# Defining the model architecture
class NN(nn.Module):

  # creating constructor
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1) # single neuron
    self.sigmoid = nn.Sigmoid() # activation function
  
  # forward pass
  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [144]:
# Important Parameters
learning_rate = 0.1
epochs = 25

In [145]:
# calling loss function from Pytorch.nn
loss_function = nn.BCELoss() # binary cross entropy

In [146]:
# Training pipeline by creating a model
model = NN(X_train_tensor.shape[1])

# defining optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate) # for weights update

# defining loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculation
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1)) # BCELoss
  
  
  # zero gradients
  optimizer.zero_grad() # reset gradients

  # backward pass
  loss.backward()

  #  parameter update
  optimizer.step() # update weights

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # printing loss
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7215216755867004
Epoch: 2, Loss: 0.5462587475776672
Epoch: 3, Loss: 0.4545881748199463
Epoch: 4, Loss: 0.39831820130348206
Epoch: 5, Loss: 0.35950636863708496
Epoch: 6, Loss: 0.33070510625839233
Epoch: 7, Loss: 0.30824971199035645
Epoch: 8, Loss: 0.2901066839694977
Epoch: 9, Loss: 0.2750473916530609
Epoch: 10, Loss: 0.2622815668582916
Epoch: 11, Loss: 0.2512754499912262
Epoch: 12, Loss: 0.24165451526641846
Epoch: 13, Loss: 0.23314738273620605
Epoch: 14, Loss: 0.22555220127105713
Epoch: 15, Loss: 0.21871545910835266
Epoch: 16, Loss: 0.21251802146434784
Epoch: 17, Loss: 0.20686599612236023
Epoch: 18, Loss: 0.2016841024160385
Epoch: 19, Loss: 0.1969112753868103
Epoch: 20, Loss: 0.1924973428249359
Epoch: 21, Loss: 0.18840065598487854
Epoch: 22, Loss: 0.18458621203899384
Epoch: 23, Loss: 0.18102435767650604
Epoch: 24, Loss: 0.17768977582454681
Epoch: 25, Loss: 0.17456059157848358


In [147]:
model.linear.weight

Parameter containing:
tensor([[ 0.1711,  0.1006,  0.1725,  0.3127,  0.1625,  0.2401,  0.2874,  0.0878,
          0.0894, -0.1615,  0.2180,  0.1231,  0.0727,  0.2775,  0.0358, -0.1741,
          0.1250,  0.0466, -0.0454, -0.0941,  0.3247,  0.2880,  0.2091,  0.1853,
          0.1034, -0.0064,  0.1490,  0.4099,  0.2777,  0.1196]],
       requires_grad=True)

In [148]:
model.linear.bias

Parameter containing:
tensor([-0.1968], requires_grad=True)

In [149]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")


Accuracy: 0.5240073800086975
